name: bench

on:
  pull_request:
    branches:
      - main

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:

      - name: install build tooling
        run: |
          sudo apt-get update
          sudo apt-get install build-essential clang gnuplot -y

      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: execute benchmark (main)
        run: |
          git checkout main
          make run-benchmarks

      - name: execute benchmark (pull_request)
        run: |
          git checkout ${{ github.head_ref }}
          make run-benchmarks

      - name: target content
        run: |
          cd target/criterion/bubble_sort
          ls -l

      # - name: publish benchmark results
      #   run: |
      #     mkdir -p gh-pages
      #     cp target/criterion/report/index.html gh-pages/index.html
      #     git clone