name: bench

on:
  pull_request:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  bench-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:

      - name: install build tooling
        run: |
          sudo apt-get update
          sudo apt-get install build-essential clang gnuplot -y

      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: execute benchmark (main)
        run: |
          git checkout main
          make run-benchmarks

      - name: execute benchmark (pull_request)
        run: |
          git checkout ${{ github.head_ref }}
          make run-benchmarks

      - name: checkout gh-pages, copy and commit report to the branch
        run: |
          git checkout gh-pages
          cp -r target/criterion/ .
          git add .
          git commit -m "benchmark results"
          git push

      - name: Setup pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'criterion'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
